#!/bin/sh

./vendor/bin/phpstan --memory-limit=512M
if [ $? -ne 0 ]; then
    echo "Erro no PHPStan"
    exit 1;
fi

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}" > /dev/null >&1;
    git add "${FILE}"
done;

exit 0;
